site_name: kskit
#TODO: add site_url: https://my-website-name.com here
# It is mandatory for deployment
site_description: Reusable tools for mammograms de-identification
site_author: Francisco ORCHARD, William MADIE

repo_url: https://github.com/Epiconcept-Paris/kskit/

nav:
  - Home: index.md
  - Quickstart: 'pages/quickstart.md'
  - Mammogram Deidentification: 'pages/deid_mammogram.md'
  - License: 'pages/license.md'
  - About: 'pages/about.md'

plugins:
# Documentation auto-generation from package's docstrings
- mkdocstrings:
    handlers:
        python:
          options:
            docstring_style: sphinx

theme:
  name: material
  favicon: img/epiconcept-logo.png
  logo: img/epiconcept-logo-xl.png

  features:
    - content.code.copy
    - content.code.select

# This section enables syntax highlighting on code blocks
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
