name: Prerelease Python Package on TestPyPI 

on:
  release:
      types: [prereleased]

jobs:
  build-prerelease:
    name: Build package for TestPyPI
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.x"
    - name: Build Package
      run: |
        python -m pip install --upgrade pip build
        python -m build
    # the following step is used to pass data to publish-test-pypi job
    # Artifacts can be used for this purpose between jobs of a same workflow run
    - name: Store the distribution packages
      uses: actions/upload-artifact@v4
      with:
          name: prerelease-package-distributions
          path: dist/
    
  publish-test-pypi:
    name: Publish prerelease to TestPyPI
    needs:
      - build-prerelease
    runs-on: ubuntu-latest
    environment:
      name: prerelease
      url: https://test.pypi.org/p/deidcm
    permissions:
        id-token: write
    steps:
    - name: Download the dists
      uses: actions/download-artifact@v4
      with:
          name: prerelease-package-distributions
          path: dist/
    - name: Publish to TestPyPi
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/
