name: Publish Python Package to PyPI- Release

on:
  release:
    types: [released]

jobs:
  pypi-publish:
    name: Publish release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/deidcm
    permissions:
      id-token: write
    steps:
      - name: Check Prerelease Status
        run: |
          echo "Prerelease status: ${{ github.event.release.prerelease }}"
          if [ "${{ github.event.release.prerelease }}" = "true" ]; then
            echo "This is a prerelease. Failing the job."
            exit 1
          fi 
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Build Package
        run: |
          python -m pip install --upgrade pip
          python3 -m build
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1