name: Publish Python Package to PyPI- Release

on:
  release:
    types: [published]

jobs:
  pypi-publish:
    name: Publish release to PyPI
    if: '!github.event.release.prerelease'
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/deidcm
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel
      - name: Build package
        run: |
          python setup.py sdist bdist_wheel
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1