name: Publish Python Package to TestPyPI - Prerelease

on:
  release:
      types: [published]

jobs:
  testpypi-publish:
    name: Publish prerelease to TestPyPI
    if: github.event.release.prerelease == true
    runs-on: ubuntu-latest
    environment: testpypi
    permissions:
        id-token: write
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.x"
    - name: Build Package
      run: |
        python -m pip install --upgrade pip
        python3 -m build
    - name: Publish to TestPyPi
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/