name: Release Python Package on PyPI 

on:
  release:
    types: [released]

jobs:
  build-release:
    name: Build package for PyPI
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.x"
    - name: Build Package
      run: |
        python -m pip install --upgrade pip build
        python -m build
    # the following step is used to pass data to publish-test-pypi job
    # Artifacts can be used for this purpose between jobs of a same workflow run
    - name: Store the distribution packages
      uses: actions/upload-artifact@v4
      with:
          name: release-package-distributions
          path: dist/

  publish-pypi:
    name: Publish release to PyPI
    needs:
      - build-release
    runs-on: ubuntu-latest
    environment:
      name: release
      url: https://pypi.org/p/deidcm
    permissions:
      id-token: write
    steps:
      - name: Download the dists
        uses: actions/download-artifact@v4
        with:
            name: release-package-distributions
            path: dist/
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1